select 
	ds,
    fsales_series_number,
    fserial_number as fnew_fseries_number,
    fissue_name,
    fanswer_name,
    case when fbrand_name='苹果' then "苹果" else "安卓" end as fbrand_name,
    case when fissue_name in ('保修情况',
                            '网络类型',
                            '机身内存',
                            'iCloud账号',
                            'iCloud账号:',
                            '存储容量',
                            '购买渠道',
                            '颜色',
                            '是否全新',
                            '制式',
                            '拆封情况',
                            '开机情况',
                            '开机情况:',
                            '型号',
                            '保修期') then "模块一"
           when fissue_name in ("有线充电",'有线充电:') and fbrand_name="苹果" then "模块一"
           when fissue_name in ('Y3声音',
                                'HOME键',
                                'Y3光线感应',
                                '无线功能（WIFI/蓝牙）',
                                '无线功能:',
                                '扬声器',
                                'Y3麦克风',
                                'Y3振动',
                                '振动',
                                '振动:',
                                'SIM 卡2',
                                '声音功能（麦克风/扬声器/听筒）',
                                '声音功能（麦克风/扬声器/听筒）:',
                                'Y3蓝牙',
                                '听筒',
                                '距离感应',
                                '重力感应',
                                '通话功能',
                                '通话功能:',
                                'Y3通信功能',
                                '静音键',
                                'Y3NFC',
                                'Y3Wi-Fi',
                                '侧键功能',
                                '侧键功能:',
                                'Y3原彩功能',
                                'Y3陀螺仪',
                                '屏幕传感器功能（光线/距离感应）',
                                '屏幕传感器功能（光线/距离感应）:',
                                '触摸',
                                'Face ID',
                                'Face ID:',
                                '闪光灯功能',
                                '蓝牙功能',
                                'Y3按键功能',
                                'Y3触摸功能',
                                '面部识别',
                                'Y3充电功能',
                                '触屏功能',
                                '触屏功能:',
                                'SIM 卡1',
                                '音量增键',
                                'NFC功能',
                                'NFC功能:',
                                '音量减键',
                                '指南针',
                                '指南针:',
                                'WIFI功能',
                                '底部麦克风',
                                'Y3距离感应',
                                '电源键',
                                '副屏-触摸功能',
                                '副屏-触摸功能:'
                                ) then "模块二"
                  when fissue_name in ("有线充电",'有线充电:') and fbrand_name!="苹果" then "模块二"
                  when fissue_name in ('面容识别','面容识别:','Y3面容功能') and fbrand_name='苹果' then "模块二"
                  when fissue_name in ('指纹识别','指纹解锁','指纹解锁:','Y3指纹功能') and fbrand_name="苹果" then "模块二"
                  when fissue_name in ('外壳印渍',
                                '外壳划痕',
                                '其他显示问题',
                                '显示气泡',
                                '壳内掉漆',
                                '外壳缝隙',
                                '显示漏液',
                                'Y3屏幕显示',
                                '外壳磕碰',
                                '后摄像头外观',
                                '闪光灯外观',
                                '内屏掉漆',
                                '正面麦克风',
                                '前摄像头外观',
                                '屏幕显示',
                                '屏幕显示:',
                                '显示图像/文字印痕',
                                '光线感应',
                                '其他按键',
                                '屏幕外观',
                                '屏幕外观:',
                                '屏幕外观碎裂',
                                '指纹按键外观',
                                '屏幕外观/其他',
                                '边框背板',
                                '边框背板:',
                                '外壳破损',
                                '显示进灰',
                                '显示老化/色差',
                                'Y3屏下异物',
                                '显示色斑/压伤',
                                'Y3弯曲情况',
                                '机身弯曲',
                                '机身弯曲:',
                                '屏幕外观划痕',
                                '显示亮点/坏点',
                                '外壳弯曲变形',
                                'Y3机身外观',
                                '其他外壳外观',
                                '外壳脱胶',
                                '外壳掉漆',
                                'Y3外屏损伤',
                                '副屏-屏幕外观',
                                '副屏-屏幕外观:',
                                '折叠屏保护膜情况',
                                '折叠屏保护膜情况:',
                                'Y3折叠屏保护膜',
                                '转轴状况',
                                '转轴状况:',
                                '副屏-屏幕显示',
                                '副屏-屏幕显示:'
                                ) then "模块三"
                       when fissue_name in ('主板拆修情况',
                                '后置摄像头',
                                '后置摄像头:',
                                '无线充电',
                                '后壳维修',
                                '后壳维修:',
                                '账号',
                                '账号:',
                                '电池更换情况',
                                '电池维修情况:',
                                '数据接口',
                                '进水/受潮',
                                '进水/受潮:',
                                '软件检测',
                                'Y3账号',
                                '后摄像头维修情况',
                                '后摄像头维修情况:',
                                'Y3电池健康度',
                                '屏幕拆修情况',
                                '电池信息情况',
                                '拆修痕迹',
                                'Y3无线充电功能',
                                '无线充电功能:',
                                'Y3前置摄像头维修',
                                '耳机接口',
                                '售后案例情况',
                                '售后案例情况:',
                                '前置摄像头',
                                '前置摄像头:',
                                'Y3基带功能',
                                'Y3屏幕维修',
                                'Y3配件情况',
                                'Y3前置摄像头',
                                'ID 锁',
                                'Y3后置摄像头',
                                'Y3尾插',
                                '浸液痕迹',
                                'Y3售后案例',
                                'Y3系统使用',
                                '摄像头维修情况',
                                'Y3后置摄像头维修',
                                '机身拆修情况',
                                '尾插螺丝',
                                '音频网罩',
                                'USB联机',
                                'USB联机:',
                                '前置摄像头功能',
                                '屏幕维修情况',
                                '屏幕维修情况:',
                                '后置摄像头功能',
                                '前摄像头维修情况',
                                '前摄像头维修情况:',
                                'Y3零件维修情况',
                                'Y3进水情况',
                                'Y3主板维修',
                                'Y3定位功能',
                                '卡托',
                                '组件拆修情况',
                                '系统情况',
                                'Y3机身维修',
                                '主板维修情况',
                                '主板维修情况:',
                                '电池健康度',
                                '电池健康度:',
                                '是否可恢复出厂设置',
                                '是否可恢复出厂设置:',
                                '其他零部件情况',
                                '其他零部件情况:',
                                '副屏-维修情况',
                                '副屏-维修情况:',
                                '虹膜识别',
                                'Y3其他功能'
                                ) then "模块四" 
                    when fissue_name in ('面容识别','面容识别:','Y3面容功能') and fbrand_name!='苹果' then "模块四" 
                    when fissue_name in ('指纹识别','指纹解锁','指纹解锁:','Y3指纹功能') and fbrand_name!="苹果" then "模块四" else null end as ftype
from (
    select 
        a.*,
        b.fserial_number,
        b.fbrand_name,
        case when left(b.fserial_number,2)='NT' and e.fbusiness_id is null then upper(f.fsrouce_serial_no)
             when left(b.fserial_number,2)='NT' and e.fbusiness_id is not null then e.fbusiness_id else d.Fsales_series_number end as fsales_series_number,
        row_number()over(partition by b.fserial_number,a.fissue_name order by a.fdetect_record_id desc) as num
    from dwd.dwd_detect_back_detection_issue_and_answer_v2 as a
    left join dwd.dwd_detect_back_detect_detail as b on a.fdetect_record_id=b.fdetect_record_id
    left join drt.drt_my33310_recycle_t_order as c on b.fserial_number=c.fseries_number
    left join drt.drt_my33310_recycle_t_after_sales_order_info as d on c.forder_id=d.Fafter_sales_order_id
    left join drt.drt_my33306_hsb_sales_t_caihuoxia_after_sales as e on b.fserial_number=e.fnew_serial_no
    left join drt.drt_my33312_hsb_sales_product_t_pm_local_create_sn as f on b.fserial_number=upper(f.fserial_no)
    where left(b.fserial_number,2) in ('NT','YZ')
    and a.field_source='fdet_norm_snapshot'
    and a.ds>=to_date(date_sub(from_unixtime(unix_timestamp()),500))
)t
where num=1
and fsales_series_number is not null
and fanswer_name not like "%完好%"
and fanswer_name not like "%正常%"
